export const skills = [
  // Backend
  "Java",
  "Python",
  "PHP",
  "Ruby",
  "Node.js",
  "Go",
  "C#",
  "Kotlin",
  "Scala",
  "Rust",
  "Django",
  "Flask",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "Express.js",
  "ASP.NET",
  "Play Framework",
  "Akka",
  "MongoDB",
  // Frontend
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "TypeScript",
  "Bootstrap",
  "Sass",
  "Redux",
  "jQuery",
  "Ember.js",
  "Backbone.js",
  "Polymer",
  "Webpack",
  "Next.js",
  "Gatsby",
  "D3.js",
  "Three.js",
  "Tailwind CSS",
  // DevOps
  "Docker",
  "Kubernetes",
  "Ansible",
  "Terraform",
  "Jenkins",
  "Git",
  "Puppet",
  "Chef",
  "Vagrant",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "CI/CD",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Nagios",
  "Splunk",
  "Istio",
  "Helm",
  // QA
  "Selenium",
  "JUnit",
  "TestNG",
  "Cucumber",
  "JMeter",
  "Postman",
  "Appium",
  "Cypress",
  "LoadRunner",
  "SoapUI",
  "Gatling",
  "Mockito",
  "TestComplete",
  "Protractor",
  "PyTest",
  "Robot Framework",
  "Visual Studio Test Professional",
  "Xray Test Management",
  "Zephyr",
  "Jenkins CI",
  // Additional technologies
  "GraphQL",
  "RabbitMQ",
  "Apache Kafka",
  "Elasticsearch",
  "Apache Spark",
  "TensorFlow",
  "PyTorch",
  "Unity",
  "React Native",
  "Ionic",
  "Flutter",
  "Swift",
  "Objective-C",
  "Xamarin",
  "Electron",
  "Cordova",
  "Unity",
  "Blender",
  // Additional technologies (continued)...
  "RubyMotion",
  "Dart",
  "Hadoop",
  "Hive",
  "Pig",
  "Apache Flink",
  "Kotlin Native",
  "R",
  "Julia",
  "Groovy",
  "Clojure",
  "Haskell",
  "Erlang",
  "OCaml",
  "Lua",
  "Perl",
  "Scheme",
  "F#",
  "Powershell",
  "Shell Scripting",
  "GraphQL",
  "RESTful API",
  "SOAP",
  "OAuth",
  "JWT",
  "Firebase",
  "Realm",
  "Cassandra",
  "Redis",
  "Memcached",
  "SQLite",
  "PostgreSQL",
  "MySQL",
  "Oracle",
  "Microsoft SQL Server",
  "MongoDB",
  "Couchbase",
  "Neo4j",
  "Elasticsearch",
  "Apache Solr",
  "Redis",
  "Apache HBase",
  // Additional technologies (continued)...
  // Вставьте сюда еще 100 технологий по вашему выбору
]
